### ISSUE TITLE
How can I see the next screen ?

### ISSUE THREAD

**Issue by rachidbch** [luke8086/retronews#1]
Thanks for the hard. I love retronews as it helps me a lot avoid distraction by context switching.

When reading news, only a few ones appear. Typically less than 30 (while the screen could contain more).
When I've read/checks these news, I should have a way to see the next page of news (older news).
But I can't find a key to do that.
So basically I can only read/check the last 30 news when I'm on the "New" screen...

Am I missing something ?

**Comment by luke8086** [comment]
Hi @rachidbch, I'm glad you liked it!

> When reading news, only a few ones appear. Typically less than 30 (while the screen could contain more).

The Front-Page, Ask-HN and Show-HN tabs should show exactly the same stories as the website, except for those with disabled comments (like job ads).

> When reading news, only a few ones appear. Typically less than 30 (while the screen could contain more).

You can use `<` and `>` to navigate to prev / next page, and `g` to go to a page with specific number.

`?` should show you a help page with a list of all available commands
