### ISSUE TITLE
Articles are sorted differently than on the webpage

### ISSUE THREAD

**Issue by 82MHz** [luke8086/retronews#2]
Hi, not an issue as such, but something I noticed and don't quite understand...
When I compared the view of the HN front page in your app vs on the website I noticed that the order is different. All the articles seem to show up, but in different places. See attached screenshots for comparison.

Do you know why this is? 

![Screenshot_20230827_065733](https://github.com/luke8086/retronews/assets/16221316/cee1357b-79ea-4134-bd4b-c16608bf6e12)
![Screenshot_20230827_065958](https://github.com/luke8086/retronews/assets/16221316/61cd9c93-5f2a-4061-8192-c082eb95b678)

**Comment by luke8086** [comment]
Thanks for the report @82MHz, good catch! It should be fixed by https://github.com/luke8086/retronews/commit/ffdd51eb539735efdd7502998bb9bfc435cccb88 in `Front HN`, `Ask HN` & `Show HN` tabs. `New HN` still has different order because it uses different API.
